# Generated by Django 6.0.6 on 2026-06-27 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Papka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papkalar', to=settings.AUTH_USER_MODEL)),
                ('ota_papka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ichki_papkalar', to='storage.papka')),
            ],
            options={
                'verbose_name': 'Papka',
                'verbose_name_plural': 'Papkalar',
            },
        ),
        migrations.CreateModel(
            name='Fayl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='fayllar/')),
                ('hajm', models.BigIntegerField(default=0)),
                ('oxirgi_pozitsiya', models.JSONField(default=dict)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fayllar', to=settings.AUTH_USER_MODEL)),
                ('papka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fayllar', to='storage.papka')),
            ],
            options={
                'verbose_name': 'Fayl',
                'verbose_name_plural': 'Fayllar',
            },
        ),
    ]
